substitutions:
  name: "barcode-scanner"
  friendly_name: "Barcode Scanner"

  # Query ID für opentindb (https://opengtindb.org/api.php)
  rest_opentindb_queryid: "400000000"

  # UART-Pins für den Barcode-Scanner
  uart_tx_pin: GPIO01
  uart_rx_pin: GPIO03

packages:
  barcode: github://robirr/barcode-scanner-for-esphome/barcode.yaml@main
